# Header
menu:
  Articles: /archives
  Projects: /2015/12/29/projects
  About: /2015/12/29/about/
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/zaaack"
  weibo: "http://weibo.com/2835064591"
  douban: "#"
  mail: "mailto:zaaack@qq.com"
  facebook: "https://www.facebook.com/zackyoung.io"
  twitter: "https://twitter.com/ZaaackYoung"
  linkedin: "http://www.linkedin.com/in/%E7%9C%9F-%E6%9D%A8-45bb94100?trk=hp-identity-name"
  rss: "https://zaaack.github.io/atom.xml"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-71560274-1'
favicon: /avatar.png

#你的头像url
avatar: /avatar.png
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: zaaack
disqus: zaaack
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: aha~
